name: Benchmarks

on: push

jobs:
  Check_Pyccel_Version:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Benchmark of pyccel')
    outputs:
      old_version: ${{ steps.check_version.outputs.old_version }}
      new_version: ${{ steps.check_version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pyccel
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install pyccel
      - name: Check Version
        run: |
          old_version=$(cat current_version.txt)
          new_version=$(python3 -c "from pyccel import __version__; print(__version__)")
          echo "old_version='${old_version}'" >> $GITHUB_OUTPUT
          echo "new_version='${new_version}'" >> $GITHUB_OUTPUT
          if [ "${old_version}" == "${new_version}" ]; then
            echo "Versions are equal"
            echo "version_changed='true'" >> $GITHUB_OUTPUT
          else
            echo "Versions are different"
            echo "version_changed='false'" >> $GITHUB_OUTPUT
          fi
          echo "'${old_version}'"
          echo "'${new_version}'"
          cat $GITHUB_OUTPUT

  Benchmark_main:
    runs-on: ubuntu-latest
    if: ${{ needs.Check_Pyccel_Version.outputs.old_version == needs.Check_Pyccel_Version.outputs.new_version }}
    needs: Check_Pyccel_Version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install pyccel from source
        run: |
          git clone https://github.com/pyccel/pyccel.git
          cd pyccel
          pip3 install .
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --verbose
          echo "### Performance Comparison (as of $(time))" > version_specific_results/devel_performance_39.md
          cat bench.out >> version_specific_results/devel_performance_39.md
          cat version_specific_results/devel_performance_39.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Devel branch benchmarks failed on python 3.9!" > version_specific_results/devel_performance_39.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/devel_performance_39.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_37:

    runs-on: ubuntu-latest
    if: ${{ needs.Check_Pyccel_Version.outputs.old_version != needs.Check_Pyccel_Version.outputs.new_version }}
    needs: Check_Pyccel_Version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of ${{needs.Check_Pyccel_Version.outputs.new_version }})" > version_specific_results/pypi_performance_37.md
          cat bench.out >> version_specific_results/pypi_performance_37.md
          cat version_specific_results/pypi_performance_37.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.7 benchmarks failed!" > version_specific_results/pypi_performance_37.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_37.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_38:

    runs-on: ubuntu-latest
    if: ${{ needs.Check_Pyccel_Version.outputs.old_version != needs.Check_Pyccel_Version.outputs.new_version }}
    needs: Check_Pyccel_Version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of ${{needs.Check_Pyccel_Version.outputs.new_version }})" > version_specific_results/pypi_performance_38.md
          cat bench.out >> version_specific_results/pypi_performance_38.md
          cat version_specific_results/pypi_performance_38.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.8 benchmarks failed!" > version_specific_results/pypi_performance_38.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_38.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_39:

    runs-on: ubuntu-latest
    if: ${{ needs.Check_Pyccel_Version.outputs.old_version != needs.Check_Pyccel_Version.outputs.new_version }}
    needs: Check_Pyccel_Version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of ${{needs.Check_Pyccel_Version.outputs.new_version }})" > version_specific_results/pypi_performance_39.md
          cat bench.out >> version_specific_results/pypi_performance_39.md
          cat version_specific_results/pypi_performance_39.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.9 benchmarks failed!" > version_specific_results/pypi_performance_39.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_39.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_310:

    runs-on: ubuntu-latest
    if: ${{ needs.Check_Pyccel_Version.outputs.old_version != needs.Check_Pyccel_Version.outputs.new_version }}
    needs: Check_Pyccel_Version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of ${{needs.Check_Pyccel_Version.outputs.new_version }})" > version_specific_results/pypi_performance_310.md
          cat bench.out >> version_specific_results/pypi_performance_310.md
          cat version_specific_results/pypi_performance_310.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.10 benchmarks failed!" > version_specific_results/pypi_performance_310.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_310.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_311:

    runs-on: ubuntu-latest
    if: ${{ needs.Check_Pyccel_Version.outputs.old_version != needs.Check_Pyccel_Version.outputs.new_version }}
    needs: Check_Pyccel_Version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies (numba doesn't support 3.11 yet)
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install pyccel
          python -m pip install pythran
          python -m pip install pyperf
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose --no_numba
          echo "### Performance Comparison (as of ${{needs.Check_Pyccel_Version.outputs.new_version }})" > version_specific_results/pypi_performance_311.md
          cat bench.out >> version_specific_results/pypi_performance_311.md
          cat version_specific_results/pypi_performance_311.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.11 benchmarks failed!" > version_specific_results/pypi_performance_311.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_311.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  BuildReadme:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(github.event.head_commit.message, 'Benchmark of pyccel')}}
    needs: [Benchmark_37, Benchmark_38, Benchmark_39, Benchmark_310, Benchmark_311, Benchmark_main]

    steps:
      - uses: actions/checkout@v3
      - name: Start writing README
        run: |
          git branch
          git pull
          cat intro.md > README.md
          cat test_details.md >> README.md
          echo "## Development branch results" >> README.md
          cat version_specific_results/devel_performance_39.md >> README.md
          echo "## Python 3.7 results" >> README.md
          cat version_specific_results/pypi_performance_37.md >> README.md
          echo "## Python 3.8 results" >> README.md
          cat version_specific_results/pypi_performance_38.md >> README.md
          echo "## Python 3.9 results" >> README.md
          cat version_specific_results/pypi_performance_39.md >> README.md
          echo "## Python 3.10 results" >> README.md
          cat version_specific_results/pypi_performance_310.md >> README.md
          echo "## Python 3.11 results" >> README.md
          cat version_specific_results/pypi_performance_311.md >> README.md
        working-directory: ./.
      - name: Save newly analysed version
        run:
          echo ${{needs.Check_Pyccel_Version.outputs.new_version }} > current_version.txt
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update README and version'
          add: "['README.md', 'current_version.txt']"
          default_author: github_actions
          pull: '--rebase --autostash'
