name: Benchmarks

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Indicates if pyccel has created a new version'
        required: true
        type: boolean

jobs:

  Benchmark_37:

    runs-on: ubuntu-latest
    if: ${{ inputs.new_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of $(date))" > version_specific_results/pypi_performance_37.md
          cat bench.out >> version_specific_results/pypi_performance_37.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.7 benchmarks failed!" > version_specific_results/pypi_performance_37.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_37.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_38:

    runs-on: ubuntu-latest
    if: ${{ inputs.new_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of $(date))" > version_specific_results/pypi_performance_38.md
          cat bench.out >> version_specific_results/pypi_performance_38.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.8 benchmarks failed!" > version_specific_results/pypi_performance_37.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_38.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_39:

    runs-on: ubuntu-latest
    if: ${{ inputs.new_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of $(date))" > version_specific_results/pypi_performance_39.md
          cat bench.out >> version_specific_results/pypi_performance_39.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.9 benchmarks failed!" > version_specific_results/pypi_performance_37.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_39.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_310:

    runs-on: ubuntu-latest
    if: ${{ inputs.new_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose
          echo "### Performance Comparison (as of $(date))" > version_specific_results/pypi_performance_310.md
          cat bench.out >> version_specific_results/pypi_performance_310.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.10 benchmarks failed!" > version_specific_results/pypi_performance_37.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_310.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  Benchmark_311:

    runs-on: ubuntu-latest
    if: ${{ inputs.new_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies (numba doesn't support 3.11 yet)
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install pyccel
          python -m pip install pythran
          python -m pip install pyperf
      - name: Benchmark
        run: |
          python run_benchmark.py --pyperf --verbose --no_numba
          echo "### Performance Comparison (as of $(date))" > version_specific_results/pypi_performance_311.md
          cat bench.out >> version_specific_results/pypi_performance_311.md
        shell: bash
        working-directory: ./.
      - name: Record Failure
        run: echo "Python 3.11 benchmarks failed!" > version_specific_results/pypi_performance_37.md
        if: ${{ failure() }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Update performance comparison'
          add: 'version_specific_results/pypi_performance_311.md'
          default_author: github_actions
          pull: '--rebase --autostash'

  BuildReadme:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [Benchmark_37, Benchmark_38, Benchmark_39, Benchmark_310, Benchmark_311]

    steps:
      - uses: actions/checkout@v3
      - name: Start writing README
        run: |
          cat intro.md > README.md
          cat test_details.md >> README.md
          echo "## Python 3.7 results" >> README.md
          cat version_specific_results/pypi_performance_37.md >> README.md
          echo "## Python 3.8 results" >> README.md
          cat version_specific_results/pypi_performance_38.md >> README.md
          echo "## Python 3.9 results" >> README.md
          cat version_specific_results/pypi_performance_39.md >> README.md
          echo "## Python 3.10 results" >> README.md
          cat version_specific_results/pypi_performance_310.md >> README.md
          echo "## Python 3.11 results" >> README.md
          cat version_specific_results/pypi_performance_311.md >> README.md
        working-directory: ./.
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Update README'
          add: 'README.md'
          default_author: github_actions
          pull: '--rebase --autostash'
